language: node_js
node_js: "8"

install:
  - (cd matchmaker-api && npm install)
  - (cd matchmaker-ui && npm install)

script: true
  # - (cd matchmaker-api && npm test)
  # - (cd matchmaker-ui && npm test)
