import {NotFoundException} from "./exceptions";
import {getById, getByToken, ISharedLink, save} from "./user-database";

export async function login(token: string): Promise<string> {
    let user = await getByToken(token);

    if (!user) {
        user = {
            sharedLinks: [],
            token,
        };
        await save(user);
    }

    return user.id as string; // "id" generated by database
}

export async function createSharedLink(userId: string): Promise<ISharedLink> {
    const user = await getById(userId);
    if (!user) {
        throw new NotFoundException();
    }

    const sharedLink: ISharedLink = {
        link: Date.now().toString(),
        matchIds: [],
    };
    user.sharedLinks.push(sharedLink);

    return Promise.resolve(sharedLink);
}

export async function getSharedLinks(userId: string): Promise<ISharedLink[]> {
    const user = await getById(userId);
    if (!user) {
        throw new NotFoundException();
    }
    return Promise.resolve(user.sharedLinks);
}

export async function updateSharedLinkLinks(userId: string, sharedLinkLink: string, matchIds: string[]): Promise<ISharedLink> {
    const user = await getById(userId);
    if (!user) {
        throw new NotFoundException();
    }

    const sharedLink = user.sharedLinks.find((it) => it.link === sharedLinkLink);
    if (!sharedLink) {
        throw new NotFoundException();
    }

    sharedLink.matchIds = matchIds;

    return Promise.resolve(sharedLink);
}

export async function deleteSharedLink(userId: string, sharedLinkLink: string): Promise<ISharedLink> {
    const user = await getById(userId);
    if (!user) {
        throw new NotFoundException();
    }

    const index = user.sharedLinks.findIndex((it) => it.link === sharedLinkLink);
    if (index === -1) {
        throw new NotFoundException();
    }

    const sharedLink = user.sharedLinks[index];
    user.sharedLinks.splice(index, 1);

    return Promise.resolve(sharedLink);
}
